name: Build and deploy Node.js app to Azure Web App - udacity-jmeckel-bot-web-app-managed

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd sdk-bot  # Navigate to the sdk-bot folder
          npm install
          npm run build --if-present

      - name: Upload sdk-bot artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app-sdk-bot
          path: sdk-bot

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./website

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Clean workspace
        run: rm -rf ./*

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-sdk-bot

      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website

      - name: List workspace files
        run: find . -path './node_modules' -prune -o -print

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_39009BB6F9B04D539890AEE1A4DCA557 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B397B7930A74201A1354807150DD660 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_358738C923AB411C9BBEBD8A97DA3A87 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'udacity-jmeckel-bot-web-app-managed'
          slot-name: 'Production'
          package: .